---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-api
spec:
  selector:
    matchLabels:
      app: dice-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dice-api
    spec:
      containers:
        - image: genzouw/dice-api:1.0.5
          imagePullPolicy: Always
          name: dice-api
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: service-dice-api
spec:
  type: ClusterIP
  selector:
    app: dice-api
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 9001
      targetPort: 80
